server.port=8080

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:C:/Users/18313/Desktop/PICC_GPSMap/db.sqlite3
spring.datasource.username=
spring.datasource.password=